import { config } from "./config.js";
import { googleAccessToken,googleCredentialsAvailable,googleJson } from "./google.js";

export function rangeDates(days,now=new Date()){const safe=[7,28,90].includes(+days)?+days:28;const end=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate()-2));const start=new Date(end);start.setUTCDate(start.getUTCDate()-safe+1);const previousEnd=new Date(start);previousEnd.setUTCDate(previousEnd.getUTCDate()-1);const previousStart=new Date(previousEnd);previousStart.setUTCDate(previousStart.getUTCDate()-safe+1);const iso=d=>d.toISOString().slice(0,10);return {days:safe,start:iso(start),end:iso(end),previousStart:iso(previousStart),previousEnd:iso(previousEnd)};}
const disconnected=(label,message)=>({label,status:"pending",message});
const num=value=>Number(value||0);
const dimensions=report=>(report.rows||[]).map(row=>({name:row.dimensionValues?.map(v=>v.value).join(" / ")||"Unknown",value:num(row.metricValues?.[0]?.value)}));
async function ga4Report(token,cfg,range,fetcher){
  const endpoint=`https://analyticsdata.googleapis.com/v1beta/properties/${cfg.GA4_PROPERTY_ID}:batchRunReports`;
  const metricNames=["activeUsers","sessions","screenPageViews","eventCount","keyEvents"];
  const summary=(startDate,endDate)=>({dateRanges:[{startDate,endDate}],metrics:metricNames.map(name=>({name}))});
  const ranked=(dimension,metric="sessions",limit=10)=>({dateRanges:[{startDate:range.start,endDate:range.end}],dimensions:[{name:dimension}],metrics:[{name:metric}],orderBys:[{metric:{metricName:metric},desc:true}],limit});
  const event=(names)=>({dateRanges:[{startDate:range.start,endDate:range.end}],dimensions:[{name:"eventName"}],metrics:[{name:"eventCount"}],dimensionFilter:{filter:{fieldName:"eventName",inListFilter:{values:names}}}});
  const reports=[summary(range.start,range.end),summary(range.previousStart,range.previousEnd),{dateRanges:[{startDate:range.start,endDate:range.end}],dimensions:[{name:"date"}],metrics:[{name:"activeUsers"}],orderBys:[{dimension:{dimensionName:"date"}}]},ranked("landingPagePlusQueryString"),ranked("sessionDefaultChannelGroup"),ranked("sessionSourceMedium"),ranked("sessionCampaignName"),ranked("language","activeUsers"),ranked("country","activeUsers"),ranked("eventName","eventCount",25),event(["booking_cta_click","contact_cta_click","phone_click","whatsapp_click","directions_click"]),event(["form_start","booking_form_start"]),event(["form_submit_attempt","booking_form_submit_click"]),event(["form_submit_success"])];
  const batches=[];for(let index=0;index<reports.length;index+=5)batches.push(reports.slice(index,index+5));const responses=await Promise.all(batches.map(requests=>googleJson(endpoint,token,{method:"POST",body:JSON.stringify({requests})},fetcher)));const r=responses.flatMap(data=>data.reports||[]);
  const metricRow=rep=>Object.fromEntries(metricNames.map((name,i)=>[name,num(rep?.rows?.[0]?.metricValues?.[i]?.value)]));
  const eventTotal=rep=>(rep?.rows||[]).reduce((sum,row)=>sum+num(row.metricValues?.[0]?.value),0);const interest=eventTotal(r[10]),started=eventTotal(r[11]),attempted=eventTotal(r[12]),success=eventTotal(r[13]);
  return {label:"Google Analytics 4",status:"connected",message:"Live aggregate website reporting is connected.",summary:metricRow(r[0]),previous:metricRow(r[1]),trend:(r[2]?.rows||[]).map(row=>({date:row.dimensionValues[0].value,value:num(row.metricValues[0].value)})),landingPages:dimensions(r[3]),channels:dimensions(r[4]),sources:dimensions(r[5]),campaigns:dimensions(r[6]),languages:dimensions(r[7]),locations:dimensions(r[8]),events:dimensions(r[9]),funnel:{interest,started,attempted,success,completionRate:started?Math.round(success/started*100):0}};
}
async function gscReport(token,cfg,range,fetcher){
  const site=encodeURIComponent(cfg.GSC_SITE_URL),endpoint=`https://searchconsole.googleapis.com/webmasters/v3/sites/${site}/searchAnalytics/query`;
  const query=async(startDate,endDate,dimensions=[],rowLimit=10)=>googleJson(endpoint,token,{method:"POST",body:JSON.stringify({startDate,endDate,dimensions,rowLimit,dataState:"final"})},fetcher);
  const [current,previous,queries,pages,devices,sitemaps,trend]=await Promise.all([query(range.start,range.end),query(range.previousStart,range.previousEnd),query(range.start,range.end,["query"],50),query(range.start,range.end,["page"],20),query(range.start,range.end,["device"],10),googleJson(`https://searchconsole.googleapis.com/webmasters/v3/sites/${site}/sitemaps`,token,{},fetcher),query(range.start,range.end,["date"],25000)]);
  const sum=rows=>{const list=rows||[];const clicks=list.reduce((n,r)=>n+num(r.clicks),0),impressions=list.reduce((n,r)=>n+num(r.impressions),0);return {clicks,impressions,ctr:impressions?clicks/impressions:0,ctrPercent:impressions?clicks/impressions*100:0,position:impressions?list.reduce((n,r)=>n+num(r.position)*num(r.impressions),0)/impressions:0};};
  const normalized=rows=>(rows||[]).map(r=>({name:r.keys?.join(" / ")||"Unknown",clicks:num(r.clicks),impressions:num(r.impressions),ctr:num(r.ctr),position:num(r.position)}));const q=normalized(queries.rows);
  return {label:"Google Search Console",status:"connected",message:"The production domain property is linked and reporting finalized search data.",summary:sum(current.rows),previous:sum(previous.rows),trend:(trend.rows||[]).map(r=>({date:r.keys?.[0]||"",clicks:num(r.clicks),impressions:num(r.impressions),ctr:num(r.ctr),position:num(r.position)})).sort((a,b)=>a.date.localeCompare(b.date)),queries:q.slice(0,20),pages:normalized(pages.rows),devices:normalized(devices.rows),opportunities:q.filter(x=>x.position>=4&&x.position<=20).sort((a,b)=>b.impressions-a.impressions).slice(0,10).map(x=>({query:x.name,...x})),sitemaps:(sitemaps.sitemap||[]).map(s=>({path:s.path,status:num(s.errors)+num(s.warnings)>0?"Review":"Success",submitted:(s.contents||[]).reduce((n,c)=>n+num(c.submitted),0),lastSubmitted:s.lastSubmitted?.slice(0,10)||""}))};
}
async function gtmReport(token,cfg,fetcher){
  const base=`https://tagmanager.googleapis.com/tagmanager/v2/accounts/${cfg.GTM_ACCOUNT_ID}/containers/${cfg.GTM_CONTAINER_ID}`;const workspace=`${base}/workspaces/${cfg.GTM_WORKSPACE_ID}`;
  const [tags,triggers,variables,status,live]=await Promise.all([googleJson(`${workspace}/tags`,token,{},fetcher),googleJson(`${workspace}/triggers`,token,{},fetcher),googleJson(`${workspace}/variables`,token,{},fetcher),googleJson(`${workspace}/status`,token,{},fetcher),googleJson(`${base}/versions:live`,token,{},fetcher)]);
  const inventory=(tags.tag||[]).map(t=>({name:t.name,type:t.type,paused:Boolean(t.paused),triggers:(t.firingTriggerId||[]).join(", ")||"None"}));const ga=inventory.filter(t=>/googtag|gaawc|ua|google/i.test(t.type)||/GA4|Google Tag/i.test(t.name));
  const broad=(triggers.trigger||[]).filter(t=>["click","formSubmission"].includes(t.type)&&!(t.filter||[]).length);
  return {label:"Google Tag Manager",status:"connected",message:`Container ${cfg.GTM_PUBLIC_ID} is accessible through the read-only API.`,publicId:cfg.GTM_PUBLIC_ID,tags:inventory,triggers:(triggers.trigger||[]).length,variables:(variables.variable||[]).length,pendingChanges:(status.workspaceChange||[]).length,mergeConflicts:(status.mergeConflict||[]).length,publishedVersion:live.containerVersionId||"Available",singleGoogleTag:ga.length===1,checks:[{name:"Single Google tag",status:ga.length===1?"good":"warning",detail:`${ga.length} Google/GA tag${ga.length===1?"":"s"} found.`},{name:"Broad click or form triggers",status:broad.length?"warning":"good",detail:broad.length?`${broad.length} unrestricted trigger(s) require review.`:"No unrestricted All Clicks or All Forms trigger found."},{name:"Paused tags",status:inventory.some(t=>t.paused)?"warning":"good",detail:`${inventory.filter(t=>t.paused).length} paused tag(s).`}]};
}
async function operations(cfg,fetcher){const targets=[["Production site",cfg.PUBLIC_SITE_ORIGIN],["robots.txt",`${cfg.PUBLIC_SITE_ORIGIN}/robots.txt`],["sitemap.xml",`${cfg.PUBLIC_SITE_ORIGIN}/sitemap.xml`]];const checks=await Promise.all(targets.map(async([label,url])=>{const start=Date.now();try{const response=await fetcher(url,{method:"GET",headers:{"User-Agent":"TCFR-Admin-Monitor/1.0"}});return {label,value:`${response.status} · ${Date.now()-start} ms`,status:response.ok?"good":"error"};}catch{return {label,value:"Unavailable",status:"error"};}}));return {label:"Cloudflare & site operations",status:checks.every(c=>c.status==="good")?"good":"warning",message:"Availability, robots and sitemap are checked without reading guest data.",checks};}
export async function buildDashboard(env,days,fetcher=fetch){const cfg=config(env),range=rangeDates(days);let ga4=disconnected("Google Analytics 4","Add the read-only Google service account to connect reporting."),searchConsole=disconnected("Google Search Console","Add the read-only Google service account to connect search reporting."),tagManager={...disconnected("Google Tag Manager","Add the read-only Google service account to connect inventory reporting."),publicId:cfg.GTM_PUBLIC_ID,tags:[],checks:[]};let googleError="";
  if(googleCredentialsAvailable(env)){try{const token=await googleAccessToken(env,fetcher);const results=await Promise.allSettled([ga4Report(token,cfg,range,fetcher),gscReport(token,cfg,range,fetcher),gtmReport(token,cfg,fetcher)]);const fallbacks=[ga4,searchConsole,tagManager],labels=["GA4","Search Console","Tag Manager"],errors=[];const resolved=results.map((result,index)=>{if(result.status==="fulfilled")return result.value;const message=result.reason?.message||"Unknown Google API error";errors.push(`${labels[index]}: ${message}`);return {...fallbacks[index],status:"error",message:`Connection failed: ${message}`};});[ga4,searchConsole,tagManager]=resolved;googleError=errors.join(" | ");}catch(error){googleError=error.message;ga4.status=searchConsole.status=tagManager.status="error";ga4.message=searchConsole.message=tagManager.message=`Authorization failed: ${googleError}`;}}
  const ops=await operations(cfg,fetcher);const businessProfile={label:"Google Business Profile",status:"pending",message:"Owner access to one location is confirmed. Performance API OAuth authorization is still required."};
  const actions=[];if(!googleCredentialsAvailable(env))actions.push("Authorize the read-only Google service account for GA4, Search Console, and Tag Manager, then add its encrypted credentials to Cloudflare.");if(ga4.funnel&&!ga4.funnel.success)actions.push("Confirm that the next real successful form submission appears as form_submit_success before marking it as a key event.");actions.push("Recheck GA4 consent diagnostics after sufficient production traffic; the account currently labels the consent signals inactive.");actions.push("Authorize the Google Business Profile Performance API when the Google project is approved.");
  return {generatedAt:new Date().toISOString(),range,platform:{ga4PropertyId:cfg.GA4_PROPERTY_ID,ga4StreamId:cfg.GA4_STREAM_ID,ga4MeasurementId:cfg.GA4_MEASUREMENT_ID,gscProperty:cfg.GSC_SITE_URL,gtmPublicId:cfg.GTM_PUBLIC_ID},ga4,searchConsole,tagManager,businessProfile,operations:ops,brief:{actions:actions.slice(0,4)},diagnostics:{googleError:googleError||undefined}};
}
