import { buildRoomPair } from './render_room_pair.mjs';
const paths={en:'/rooms/common-areas/',es:'/es/habitaciones/areas-comunes/'};
const copy={
 en:{
  name:'Common Areas',title:'Common Areas & Shared Kitchen | The Cloud Forest Retreat',description:'Explore the shared living room, kitchen and guest bathroom at The Cloud Forest Retreat near Quito. See photos and plan the practical details of your stay.',
  home:'/',hub:'/rooms/',booking:'/booking/',contact:'/contact/',common:'/rooms/',homeLabel:'Home',hubLabel:'Rooms',kicker:'Shared spaces. Time to settle in.',
  heroImage:'tcfr_rooms_common_area_hero_01.jpg',heroAlt:'Retreat exterior with covered seating and a hammock by the common areas',
  lead:'The shared living room and kitchen give you space beyond your bedroom to read, talk and plan the day. A guest half bathroom serves the common areas. Explore the photos, then ask your host about kitchen use and meal arrangements for your stay.',
  book:'Check stay availability',compare:'Compare all rooms',ask:'Ask about shared spaces',
  highlights:[['Living room','Seating for time between outings'],['Shared kitchen','Confirm use and meals with the host'],['Guest bathroom','A half bathroom in the common areas']],
  featuresLabel:'Around the retreat',featuresTitle:'Space beyond your bedroom',featuresIntro:'These areas are shared with other guests. They complement your room and offer different places to spend time throughout the day.',
  features:[['A place to pause','Read, journal or relax in the living room between time outdoors. Seating and windows connect the indoor space with the surrounding landscape.'],['A practical kitchen','The shared kitchen and table offer a place for food preparation and time together. Confirm permitted use, available equipment and food storage with your host.'],['A convenient guest bathroom','The common areas have a guest half bathroom. It is separate from the full hallway bathroom shared by the Sunrise and Sunset rooms.']],
  photosLabel:'See the spaces',galleryTitle:'Inside the shared living room',galleryIntro:'Original retreat photos show the seating, windows and interior layout.',
  photos:[['tcfr_rooms_common_area_living_room_01.jpeg','Seating and windows in the retreat living room','A place to sit and unwind'],['tcfr_rooms_common_area_living_room_02.jpeg','Another view of the shared living room and seating','The shared living room layout']],
  fitTitle:'Make time between outings',fitText:'The common areas give you a place to gather before a walk or settle in after birdwatching. Enjoy a book, conversation or quiet time while respecting other guests who are resting.',
  sharedTitle:'Choose your private room',sharedText:'Shared spaces are part of the retreat layout, not a separate bedroom option. Compare the Panoramic Suite, Sunrise Room and Sunset Room for sleeping arrangements, views and bathroom details before requesting availability.',sharedLink:'Compare bedroom options',
  planningLabel:'Before your stay',practicalTitle:'Confirm the details that matter to you',practicalIntro:'A short conversation with the host helps you plan how you will use the shared spaces.',
  practical:[['Kitchen use','Ask about access, cooking equipment and storage before planning meals or shopping.'],['Meals and drinks','Confirm what your rate includes and discuss dietary needs. Kitchen access does not by itself mean meals are included.'],['Shared-space etiquette','Ask about quiet hours and any house rules. Keep seating, tables and work surfaces ready for the next guest.'],['Access needs','Describe any mobility or access requirements before booking so the host can explain the layout and help assess suitability.']],
  faqLabel:'Helpful answers',faqTitle:'Common Areas questions',faqIntro:'Practical answers about shared facilities and how they fit into your stay.',
  faqs:[['Are the common areas private to my room?','No. The living room, kitchen and common-area guest bathroom are shared spaces. Your bedroom is a separate choice; compare the room pages for its layout and bathroom arrangements.'],['Can guests use the kitchen?','The retreat has a shared kitchen. Confirm current access, available equipment, storage and any house rules with the host before planning to cook.'],['Are meals included with kitchen access?','Do not assume meals are included because there is a shared kitchen. Ask the host what your quoted rate includes and discuss meals and dietary needs for your dates.'],['Is the common-area bathroom the Sunrise and Sunset bathroom?','No. The common areas have a guest half bathroom. The Sunrise and Sunset rooms share a separate full bathroom in the hallway outside those bedrooms.']],
  relatedLabel:'Continue exploring',relatedTitle:'Connect your room with the rest of your stay',related:[['Panoramic Suite','/rooms/panoramic-suite/'],['Sunrise Room','/rooms/sunrise-room/'],['Sunset Room','/rooms/sunset-room/'],['Retreat amenities','/features/amenities/'],['Birdwatching at the retreat','/birdwatching-lodge-ecuador/'],['Cloud Forest Lodge Near Quito','/cloud-forest-lodge-near-quito/'],['What to pack','/what-to-pack-cloud-forest-ecuador/'],['Getting to the retreat','/blog/how-to-get-to-cloud-forest-retreat/']],
  reviewTitle:'Guests share their retreat experience',reviewIntro:'These reviews describe stays at the retreat as a whole.',
  extraTitle:'Kitchen and guest bathroom',extraIntro:'See the shared kitchen and the washbasin in the common-area half bathroom. Confirm practical arrangements directly with your host.',extraAlts:['Shared kitchen and dining table beneath a timber ceiling','Washbasin and wooden counter in the common-area half bathroom'],extraCaptions:['The shared kitchen and table','The guest half bathroom'],videoLabels:['Watch the kitchen video','Watch the living room video']
 },
 es:{
  name:'Áreas Comunes',title:'Áreas Comunes y Cocina Compartida | The Cloud Forest Retreat',description:'Conoce la sala, cocina compartida y baño de visitas de The Cloud Forest Retreat cerca de Quito. Mira las fotos y consulta los detalles para tu estadía.',
  home:'/es/',hub:'/es/habitaciones/',booking:'/es/reservas/',contact:'/es/contacto/',common:'/es/habitaciones/',homeLabel:'Inicio',hubLabel:'Habitaciones',kicker:'Espacios compartidos. Tiempo para descansar.',
  heroImage:'tcfr_rooms_common_area_hero_01.jpg',heroAlt:'Exterior del refugio con asientos cubiertos y hamaca junto a las áreas comunes',
  lead:'La sala y la cocina compartidas ofrecen espacio fuera de tu habitación para leer, conversar y planificar el día. Las áreas comunes cuentan con un medio baño de visitas. Mira las fotos y consulta con tu anfitrión el uso de la cocina y las comidas para tu estadía.',
  book:'Consultar disponibilidad',compare:'Comparar habitaciones',ask:'Consultar sobre las áreas comunes',
  highlights:[['Sala compartida','Un lugar para descansar entre salidas'],['Cocina compartida','Consulta su uso y las comidas'],['Baño de visitas','Medio baño en las áreas comunes']],
  featuresLabel:'Dentro del refugio',featuresTitle:'Espacio fuera de tu habitación',featuresIntro:'Estas áreas se comparten con otros huéspedes. Complementan tu habitación y ofrecen distintos lugares para disfrutar del día.',
  features:[['Un lugar para hacer una pausa','Lee, escribe o descansa en la sala entre salidas. Los asientos y las ventanas conectan el interior con el paisaje que rodea al refugio.'],['Una cocina práctica','La cocina y la mesa compartidas ofrecen espacio para preparar alimentos y pasar tiempo juntos. Confirma con tu anfitrión el uso permitido, los utensilios disponibles y el almacenamiento.'],['Un baño de visitas cercano','Las áreas comunes tienen un medio baño de visitas. Es distinto del baño completo del pasillo que comparten las habitaciones Amanecer y Atardecer.']],
  photosLabel:'Conoce los espacios',galleryTitle:'Dentro de la sala compartida',galleryIntro:'Las fotos originales del refugio muestran los asientos, las ventanas y la distribución interior.',
  photos:[['tcfr_rooms_common_area_living_room_01.jpeg','Asientos y ventanas de la sala compartida del refugio','Un lugar para sentarse y descansar'],['tcfr_rooms_common_area_living_room_02.jpeg','Otra vista de los asientos y la sala compartida','La distribución de la sala']],
  fitTitle:'Disfruta el tiempo entre salidas',fitText:'Las áreas comunes ofrecen un lugar para reunirse antes de caminar o descansar después de observar aves. Disfruta de un libro, una conversación o un momento tranquilo, respetando a los huéspedes que descansan.',
  sharedTitle:'Elige tu habitación privada',sharedText:'Los espacios compartidos forman parte del refugio y no son una opción de dormitorio. Compara la Suite Panorámica, Amanecer y Atardecer para conocer las camas, vistas y baños antes de consultar disponibilidad.',sharedLink:'Comparar opciones de habitación',
  planningLabel:'Antes de tu estadía',practicalTitle:'Confirma los detalles que necesitas',practicalIntro:'Una breve conversación con tu anfitrión te ayudará a planificar el uso de los espacios compartidos.',
  practical:[['Uso de la cocina','Consulta el acceso, los utensilios y el almacenamiento antes de planificar comidas o compras.'],['Comidas y bebidas','Confirma qué incluye la tarifa y conversa sobre tus necesidades alimentarias. Tener acceso a una cocina no significa que las comidas estén incluidas.'],['Convivencia','Consulta los horarios de silencio y las normas de la casa. Deja los asientos, mesas y superficies listos para el siguiente huésped.'],['Necesidades de acceso','Explica cualquier necesidad de movilidad o acceso antes de reservar para que el anfitrión describa la distribución y te ayude a evaluar si se adapta a ti.']],
  faqLabel:'Respuestas útiles',faqTitle:'Preguntas sobre las áreas comunes',faqIntro:'Respuestas prácticas sobre los espacios compartidos y su uso durante tu estadía.',
  faqs:[['¿Las áreas comunes son privadas para mi habitación?','No. La sala, la cocina y el baño de visitas de las áreas comunes son compartidos. Tu dormitorio es una elección aparte; consulta las páginas de habitaciones para conocer su distribución y baño.'],['¿Los huéspedes pueden usar la cocina?','El refugio cuenta con una cocina compartida. Confirma con el anfitrión el acceso actual, los utensilios, el almacenamiento y las normas antes de planificar cocinar.'],['¿El acceso a la cocina incluye comidas?','No asumas que las comidas están incluidas por tener una cocina compartida. Consulta qué incluye tu tarifa y conversa sobre comidas y necesidades alimentarias para tus fechas.'],['¿El baño común es el de Amanecer y Atardecer?','No. Las áreas comunes tienen un medio baño de visitas. Amanecer y Atardecer comparten otro baño completo en el pasillo, afuera de esas habitaciones.']],
  relatedLabel:'Sigue explorando',relatedTitle:'Conecta tu habitación con el resto de la estadía',related:[['Suite Panorámica','/es/habitaciones/suite-panoramica/'],['Habitación Amanecer','/es/habitaciones/habitacion-amanecer/'],['Habitación Atardecer','/es/habitaciones/habitacion-atardecer/'],['Amenidades del refugio','/es/caracteristicas/amenidades/'],['Avistamiento de aves','/es/lodge-avistamiento-aves-ecuador/'],['Lodge de bosque nublado cerca de Quito','/es/lodge-bosque-nublado-cerca-de-quito/'],['Qué llevar','/es/que-llevar-bosque-nublado-ecuador/'],['Cómo llegar','/es/blog/como-llegar-cloud-forest-retreat/']],
  reviewTitle:'Los huéspedes cuentan su experiencia',reviewIntro:'Estas reseñas describen estadías en el refugio en general.',
  extraTitle:'Cocina y baño de visitas',extraIntro:'Conoce la cocina compartida y el lavabo del medio baño de las áreas comunes. Confirma los detalles de uso directamente con tu anfitrión.',extraAlts:['Cocina y mesa compartidas bajo un techo de madera','Lavabo y encimera de madera del medio baño de visitas'],extraCaptions:['La cocina y la mesa compartidas','El medio baño de visitas'],videoLabels:['Ver el video de la cocina','Ver el video de la sala']
 }
};
for(const p of Object.values(copy)){
 p.entityType='Place';p.pageType='common_areas_page';
 p.extraSection=`      <section class="roomsSection roomsGuidance" aria-labelledby="shared-facilities-title" data-analytics-section="shared_facilities">
        <header class="roomsSectionHeading"><h2 id="shared-facilities-title">${p.extraTitle}</h2><p>${p.extraIntro}</p></header>
        <div class="suiteGallery roomGallery--two">
${['tcfr_rooms_common_area_kitchen_03.jpg','tcfr_rooms_common_area_half_bathroom_01.jpeg'].map((f,i)=>`          <figure><img src="/assets/images/pages/rooms/${f}" alt="${p.extraAlts[i]}" loading="lazy" decoding="async" /><figcaption>${p.extraCaptions[i]}</figcaption></figure>`).join('\n')}
        </div>
        <div class="roomsShowcase__actions">
${['lz7DEZKFkX8','aPklWBKloRc'].map((id,i)=>`          <a class="btn secondary" href="https://www.youtube.com/watch?v=${id}" target="_blank" rel="noopener" data-analytics-event="video_click" data-analytics-location="shared_facilities" data-analytics-page-type="common_areas_page" data-analytics-label="${i===0?'Kitchen':'Living room'} video">${p.videoLabels[i]}</a>`).join('\n')}
        </div>
      </section>`;
}
await buildRoomPair(copy,paths,'common-areas');
