import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const {chromium}=require(path.join(os.homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));
const output='/tmp/tcfr-nature-legal-qa';await fs.mkdir(output,{recursive:true});
const pairs=[
 ['pair_019','/features/pululahua/','/es/caracteristicas/pululahua/','nature-birding'],
 ['pair_020','/features/rio-guayllabamba/','/es/caracteristicas/rio-guayllabamba/','nature-birding'],
 ['pair_021','/privacy-policy/','/es/politica-de-privacidad/','legal']
];
const origin='https://thecloudforestretreat.com',reports=[];
const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
for(const [pair,en,es,cluster] of pairs)for(const width of [390,768,1440])for(const route of [en,es]){
 const page=await browser.newPage({viewport:{width,height:width===390?844:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(`http://127.0.0.1:4173${route}?utm_source=${pair}_qa&utm_medium=test`,{waitUntil:'domcontentloaded'});await page.waitForSelector('#siteFooter footer');
 await page.evaluate(()=>window.TCFRConsent.accept());
 await page.evaluate(async()=>{document.querySelectorAll('img[loading=lazy]').forEach(i=>i.loading='eager');await Promise.all([...document.images].map(i=>i.decode().catch(()=>{})));await document.fonts.ready});
 const result=await page.evaluate(()=>{const graph=[...document.querySelectorAll('script[type="application/ld+json"]')].flatMap(s=>JSON.parse(s.textContent)['@graph']||[]),faq=[...document.querySelectorAll('.tcfrFaq details')].map(d=>[d.querySelector('summary').textContent.trim(),d.querySelector('p').textContent.trim()]),schemaFaq=graph.find(n=>n['@type']==='FAQPage')?.mainEntity.map(q=>[q.name,q.acceptedAnswer.text])||[],groups=[...document.querySelectorAll('.natureSpecies,.natureLandscape,.natureObserve__grid')].map(g=>[...g.children].map(e=>{const r=e.getBoundingClientRect();return {top:r.top,width:r.width,height:r.height}}));return {h1:document.querySelectorAll('h1').length,title:document.title,description:document.querySelector('[name=description]').content,canonical:document.querySelector('[rel=canonical]').href,alternates:[...document.querySelectorAll('[rel=alternate][hreflang]')].map(a=>[a.hreflang,a.href]),faqMatches:JSON.stringify(faq)===JSON.stringify(schemaFaq),faqCount:faq.length,webpage:graph.find(n=>n['@type']==='WebPage'),lodging:graph.find(n=>Array.isArray(n['@type'])&&n['@type'].includes('LodgingBusiness')),overflow:document.documentElement.scrollWidth>innerWidth+1,groups,lang:document.querySelector('#siteHeader .tcfr-langBtn[aria-current=page]')?.dataset.lang,langLinks:[...document.querySelectorAll('#siteHeader .tcfr-langBtn')].map(a=>[a.dataset.lang,new URL(a.href).pathname]),includes:document.querySelector('#siteHeader').textContent.length>50&&document.querySelector('#siteFooter').textContent.length>50,brokenImages:[...document.images].filter(i=>!i.complete||!i.naturalWidth).map(i=>i.src),untracked:[...document.querySelectorAll('main a')].filter(a=>!a.dataset.analyticsEvent).map(a=>a.href),links:[...document.querySelectorAll('main a')].map(a=>a.getAttribute('href')),scripts:[...document.scripts].map(s=>s.src),styles:[...document.querySelectorAll('link[rel=stylesheet]')].map(s=>s.href),pageTop:getComputedStyle(document.documentElement).getPropertyValue('--tcfr-page-top').trim(),attribution:Object.fromEntries(Object.entries(localStorage).filter(([k])=>/tcfr/i.test(k))),cluster:document.body.dataset.tcfrCluster,template:document.body.dataset.tcfrTemplate}});
 const broken=[];for(const href of new Set(result.links)){const u=new URL(href,origin+route);if(u.origin!==origin||(u.hash&&u.pathname===route))continue;let f=path.join(process.cwd(),decodeURIComponent(u.pathname),u.pathname.endsWith('/')?'index.html':'');try{await fs.access(f)}catch{broken.push(u.pathname)}}
 const expected=[['en',origin+en],['es',origin+es],['x-default',origin+en]],lang=route.startsWith('/es/')?'es':'en';let aligned=true;if(width>640)for(const group of result.groups)for(let i=0;i<group.length;i++){for(let j=i+1;j<group.length;j++)if(Math.abs(group[i].top-group[j].top)<2&&Math.abs(group[i].height-group[j].height)>2)aligned=false}
 const checks={heading:result.h1===1,metadata:result.title.length>=30&&result.description.length>=100,canonical:result.canonical===origin+route,alternates:JSON.stringify(result.alternates)===JSON.stringify(expected),faq:result.faqCount===4&&result.faqMatches,schema:result.webpage?.url===origin+route&&!!result.lodging,responsive:!result.overflow&&aligned,language:result.lang===lang&&result.langLinks.every(([c,h])=>h===(c==='en'?en:es)),includes:result.includes,assets:!result.brokenImages.length,links:!broken.length,hooks:!result.untracked.length,attribution:JSON.stringify(result.attribution).includes(pair+'_qa'),sharedAssets:['site-config.js','head.js','attribution.js','site.js'].every(s=>result.scripts.some(u=>u.includes('/assets/js/'+s)))&&['global.css',`clusters/${cluster}.css`,'components/faq.css'].every(s=>result.styles.some(u=>u.includes('/assets/css/'+s))),cluster:result.cluster===cluster,spacing:result.pageTop===(width<=760?'12px':'18px'),errors:!errors.length};
 await page.screenshot({path:`${output}/${pair}-${lang}-${width}.png`,fullPage:true});await page.locator('.tcfrFaq summary').first().focus();await page.keyboard.press('Enter');checks.keyboard=await page.locator('.tcfrFaq details').first().evaluate(e=>e.open);
 const report={pair,route,width,pass:Object.values(checks).every(Boolean),checks,errors,broken,result};reports.push(report);console.log(JSON.stringify({pair,route,width,pass:report.pass,checks,broken,errors}));await page.close();
}
await browser.close();await fs.writeFile(output+'/results.json',JSON.stringify(reports,null,2));if(reports.some(r=>!r.pass))process.exitCode=1;
