import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const {chromium}=require(path.join(os.homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));
const output='/tmp/tcfr-planning-batch-044-046-qa';await fs.mkdir(output,{recursive:true});
const pairs=[
 ['pair_044','/quito-to-cloud-forest-distance/','/es/distancia-quito-bosque-nublado/','planning','premium-planning'],
 ['pair_045','/what-to-pack-cloud-forest-ecuador/','/es/que-llevar-bosque-nublado-ecuador/','planning','premium-planning'],
 ['pair_046','/is-cloud-forest-safe-ecuador/','/es/es-seguro-bosque-nublado-ecuador/','planning','premium-planning']
];
const origin='https://thecloudforestretreat.com',reports=[];
const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
for(const [pair,en,es,cluster,template] of pairs)for(const width of [390,768,1440])for(const route of [en,es]){
 const context=await browser.newContext({viewport:{width,height:width===390?844:1000}});
 const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(`http://127.0.0.1:4173${route}?utm_source=${pair}_qa&utm_medium=test`,{waitUntil:'domcontentloaded'});await page.waitForSelector('#siteFooter footer');
 const consentInitial=await page.evaluate(()=>({status:window.__TCFR_CONSENT_STATUS__,banner:!document.querySelector('#tcfr-consent')?.hidden,attribution:localStorage.getItem('tcfr_attribution_v1'),defaultDenied:(window.dataLayer||[]).some(x=>x&&x[0]==='consent'&&x[1]==='default'&&x[2]?.analytics_storage==='denied'),gtm:!!document.querySelector('#tcfr-gtm-loader')}));
 await page.click('[data-tcfr-consent="accept"]');
 const consentAccepted=await page.evaluate(()=>({status:window.__TCFR_CONSENT_STATUS__,saved:JSON.parse(localStorage.getItem('tcfr_consent_v1')||'null')?.choice,attribution:localStorage.getItem('tcfr_attribution_v1'),manage:!document.querySelector('#tcfr-consent-manage')?.hidden,updateGranted:(window.dataLayer||[]).some(x=>x&&x[0]==='consent'&&x[1]==='update'&&x[2]?.analytics_storage==='granted')}));
 await page.evaluate(async()=>{document.querySelectorAll('img[loading=lazy]').forEach(i=>i.loading='eager');await Promise.all([...document.images].map(i=>i.decode().catch(()=>{})));await document.fonts.ready});
 const result=await page.evaluate(()=>{const graph=[...document.querySelectorAll('script[type="application/ld+json"]')].flatMap(s=>JSON.parse(s.textContent)['@graph']||[]),faq=[...document.querySelectorAll('.tcfrFaq details')].map(d=>[d.querySelector('summary').textContent.trim(),d.querySelector('p').textContent.trim()]),schemaFaq=graph.find(n=>n['@type']==='FAQPage')?.mainEntity.map(q=>[q.name,q.acceptedAnswer.text])||[],groups=[...document.querySelectorAll('.stayReasons__grid,.stayPath__grid,.natureSpecies,.natureLandscape,.natureObserve__grid,.planningTopics,.planningCompare__choices,.planningSteps__grid')].map(g=>[...g.children].map(e=>{const r=e.getBoundingClientRect();return {top:r.top,width:r.width,height:r.height}}));return {h1:document.querySelectorAll('h1').length,title:document.title,description:document.querySelector('[name=description]').content,canonical:document.querySelector('[rel=canonical]').href,alternates:[...document.querySelectorAll('[rel=alternate][hreflang]')].map(a=>[a.hreflang,a.href]),faqMatches:JSON.stringify(faq)===JSON.stringify(schemaFaq),faqCount:faq.length,webpage:graph.find(n=>n['@type']==='WebPage'),lodging:graph.find(n=>Array.isArray(n['@type'])&&n['@type'].includes('LodgingBusiness')),overflow:document.documentElement.scrollWidth>innerWidth+1,groups,lang:document.querySelector('#siteHeader .tcfr-langBtn[aria-current=page]')?.dataset.lang,langLinks:[...document.querySelectorAll('#siteHeader .tcfr-langBtn')].map(a=>[a.dataset.lang,new URL(a.href).pathname]),includes:document.querySelector('#siteHeader').textContent.length>50&&document.querySelector('#siteFooter').textContent.length>50,brokenImages:[...document.images].filter(i=>!i.complete||!i.naturalWidth).map(i=>i.src),untracked:[...document.querySelectorAll('main a')].filter(a=>!a.dataset.analyticsEvent).map(a=>a.href),links:[...document.querySelectorAll('main a')].map(a=>a.getAttribute('href')),scripts:[...document.scripts].map(s=>s.src),styles:[...document.querySelectorAll('link[rel=stylesheet]')].map(s=>s.href),pageTop:getComputedStyle(document.documentElement).getPropertyValue('--tcfr-page-top').trim(),cluster:document.body.dataset.tcfrCluster,template:document.body.dataset.tcfrTemplate,consentTitle:document.querySelector('#tcfr-consent-title')?.textContent.trim()}});
 const broken=[];for(const href of new Set(result.links)){const u=new URL(href,origin+route);if(u.origin!==origin||(u.hash&&u.pathname===route))continue;let f=path.join(process.cwd(),decodeURIComponent(u.pathname),u.pathname.endsWith('/')?'index.html':'');try{await fs.access(f)}catch{broken.push(u.pathname)}}
 const expected=[['en',origin+en],['es',origin+es],['x-default',origin+en]],lang=route.startsWith('/es/')?'es':'en';let aligned=true;if(width>640)for(const group of result.groups)for(let i=0;i<group.length;i++)for(let j=i+1;j<group.length;j++)if(Math.abs(group[i].top-group[j].top)<2&&Math.abs(group[i].height-group[j].height)>2)aligned=false;
 const checks={heading:result.h1===1,metadata:result.title.length>=30&&result.title.length<=65&&result.description.length>=100&&result.description.length<=165,canonical:result.canonical===origin+route,alternates:JSON.stringify(result.alternates)===JSON.stringify(expected),faq:result.faqCount===4&&result.faqMatches,schema:result.webpage?.url===origin+route&&!!result.lodging,responsive:!result.overflow&&aligned,language:result.lang===lang&&result.langLinks.every(([c,h])=>h===(c==='en'?en:es)),includes:result.includes,assets:!result.brokenImages.length,links:!broken.length,hooks:!result.untracked.length,sharedAssets:['site-config.js','head.js','attribution.js','site.js'].every(s=>result.scripts.some(u=>u.includes('/assets/js/'+s)))&&['global.css',`clusters/${cluster}.css`,'components/faq.css'].every(s=>result.styles.some(u=>u.includes('/assets/css/'+s))),cluster:result.cluster===cluster&&result.template===template,spacing:result.pageTop===(width<=760?'12px':'18px'),errors:!errors.length,consentInitial:consentInitial.status==='unknown'&&consentInitial.banner&&consentInitial.attribution===null&&consentInitial.defaultDenied&&consentInitial.gtm,consentAccept:consentAccepted.status==='accepted'&&consentAccepted.saved==='accepted'&&String(consentAccepted.attribution).includes(pair+'_qa')&&consentAccepted.manage&&consentAccepted.updateGranted,consentLanguage:result.consentTitle===(lang==='es'?'Tu privacidad':'Your privacy')};
 await page.screenshot({path:`${output}/${pair}-${lang}-${width}.png`,fullPage:true});await page.locator('.tcfrFaq summary').first().focus();await page.keyboard.press('Enter');checks.keyboard=await page.locator('.tcfrFaq details').first().evaluate(e=>e.open);
 await page.click('#tcfr-consent-manage');await page.click('[data-tcfr-consent="reject"]');checks.consentReject=await page.evaluate(()=>window.__TCFR_CONSENT_STATUS__==='rejected'&&JSON.parse(localStorage.getItem('tcfr_consent_v1')||'null')?.choice==='rejected'&&!localStorage.getItem('tcfr_attribution_v1')&&(window.dataLayer||[]).some(x=>x&&x[0]==='consent'&&x[1]==='update'&&x[2]?.analytics_storage==='denied'));
 const report={pair,route,width,pass:Object.values(checks).every(Boolean),checks,errors,broken,result,consentInitial,consentAccepted};reports.push(report);console.log(JSON.stringify({pair,route,width,pass:report.pass,checks,broken,errors}));await context.close();
}
await browser.close();await fs.writeFile(output+'/results.json',JSON.stringify(reports,null,2));if(reports.some(r=>!r.pass))process.exitCode=1;
